name: Auto Mirror main to secondary

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to secondary repo
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: main
          destination_repo: https://x-access-token:${{ secrets.MIKEY_PAT }}@github.com/xArieN9x/mike-v02-core-sec-source.git
          destination_branch: main
          github_token: ${{ secrets.MIKEY_PAT }}
