name: Auto Mirror main to secondary

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to secondary repo
        env:
          PAT_TOKEN: ${{ secrets.MIKEY_PAT }}  # pastikan PAT ada akses full repo secondary
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote add secondary https://x-access-token:${PAT_TOKEN}@github.com/xArieN9x/mike-v02-core-sec-source.git
          git push secondary --all --force
          git push secondary --tags --force
